using System;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json.Nodes;
using System.Threading.Tasks;

namespace WisprDesktopAgent.Core
{
    public class DesktopFlowUpdater
    {
        private readonly HttpClient _httpClient;
        private readonly string _orgUrl;

        // 🔥 TOGGLE THIS
        private readonly bool forceQuotes = true;

        public DesktopFlowUpdater(string orgUrl, string accessToken)
        {
            _orgUrl = orgUrl.TrimEnd('/');

            _httpClient = new HttpClient();

            _httpClient.DefaultRequestHeaders.Authorization =
                new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", accessToken);

            _httpClient.DefaultRequestHeaders.Add("OData-MaxVersion", "4.0");
            _httpClient.DefaultRequestHeaders.Add("OData-Version", "4.0");
            _httpClient.DefaultRequestHeaders.Add("Accept", "application/json");
        }

        // ============================================================
        // MAIN METHOD (WISPR → PAD → UPDATE)
        // ============================================================
        public async Task UpdateDesktopFlowAsync(Guid flowId, string wisprScript)
        {
            if (string.IsNullOrWhiteSpace(wisprScript))
                throw new ArgumentException("Script cannot be empty");

            var padScript = ConvertWisprToPad(wisprScript);

            // 🔥 Apply quote mode if needed
            var finalDefinition = forceQuotes
                ? WrapWithQuotes(padScript)
                : padScript;

            await UpdateInternal(flowId, finalDefinition);

            Console.WriteLine("✅ Flow updated");
        }

        // ============================================================
        // STATIC TEST
        // ============================================================
        public async Task TestStaticUpdate(Guid flowId)
        {
            string staticDefinition =
            "@@ConnectionString: ''\r\n" +
            "@@Type: 'Local'\r\n" +
            "@@DesktopType: 'local'\r\n" +
            "@@DisplayName: 'Local computer'\r\n" +
            "IMPORT 'controlRepo.appmask' AS appmask\r\n" +
            "IMPORT 'imageRepo.imgrepo' AS imgrepo\r\n" +
            "@SENSITIVE: []\r\n" +
            "# Start of autogenerated actions using the recorder\r\n" +
            "System.RunApplication.RunApplication ApplicationPath: $'''C:\\\\Users\\\\GauravPatel\\\\Downloads\\\\LoanDesk_Windows_EXE_Build_Package\\\\LoanDesk_Enterprise_Executable.jar''' WindowStyle: System.ProcessWindowStyle.Normal ProcessId=> AppProcessId\r\n" +
            "@@source: 'Recorder'\r\n" +
            "UIAutomation.PopulateTextField.PopulateTextField TextField: appmask['Window \\'LoanDesk Enterprise Login\\'']['JText'] Text: 'user1'\r\n" +
            "# End of autogenerated actions using the recorder\r\n";

            var finalDefinition = forceQuotes
                ? WrapWithQuotes(staticDefinition)
                : staticDefinition;

            await UpdateInternal(flowId, finalDefinition);

            Console.WriteLine("✅ STATIC TEST SUCCESS");
        }

        // ============================================================
        // CORE UPDATE
        // ============================================================
        private async Task UpdateInternal(Guid flowId, string definition)
        {
            var getUrl = $"{_orgUrl}/api/data/v9.2/workflows({flowId})?$select=statecode";

            var getRes = await _httpClient.GetAsync(getUrl);
            var getBody = await getRes.Content.ReadAsStringAsync();

            if (!getRes.IsSuccessStatusCode)
                throw new Exception(getBody);

            var statecode = JsonNode.Parse(getBody)?["statecode"]?.GetValue<int>() ?? 0;
            bool wasActive = (statecode == 1);

            // Deactivate
            if (wasActive)
            {
                await SendPatch(flowId, new JsonObject
                {
                    ["statecode"] = 0,
                    ["statuscode"] = 1
                });
            }

            // Update definition
            await SendPatch(flowId, new JsonObject
            {
                ["definition"] = definition
            });

            // Activate
            if (wasActive)
            {
                await ActivateWorkflowAsync(flowId);
            }
        }

        // ============================================================
        // 🔥 WISPR → PAD CONVERTER (FIXED)
        // ============================================================
        private string ConvertWisprToPad(string script)
        {
            var lines = script
                .Split('\n')
                .Select(l => l.Trim())
                .Where(l => !string.IsNullOrWhiteSpace(l))
                .ToList();

            var sb = new StringBuilder();

            // Header
            sb.AppendLine("@@ConnectionString: ''");
            sb.AppendLine("@@Type: 'Local'");
            sb.AppendLine("@@DesktopType: 'local'");
            sb.AppendLine("@@DisplayName: 'Local computer'");
            sb.AppendLine("IMPORT 'controlRepo.appmask' AS appmask");
            sb.AppendLine("IMPORT 'imageRepo.imgrepo' AS imgrepo");
            sb.AppendLine("@SENSITIVE: []");

            sb.AppendLine("# Start of autogenerated actions using the recorder");

            foreach (var line in lines)
            {
                // Skip non-actions
                if (line.StartsWith("@@") ||
                    line.StartsWith("IMPORT") ||
                    line.StartsWith("@SENSITIVE") ||
                    line.StartsWith("#"))
                {
                    continue;
                }

                string fixedLine = line;

                // Fix action name
                if (fixedLine.StartsWith("System.LaunchApplication"))
                {
                    fixedLine = fixedLine.Replace(
                        "System.LaunchApplication",
                        "System.RunApplication.RunApplication"
                    );
                }

                // Add ProcessId
                if (fixedLine.StartsWith("System.RunApplication.RunApplication") &&
                    !fixedLine.Contains("ProcessId=>"))
                {
                    fixedLine += " ProcessId=> AppProcessId";
                }

                // Fix escaping
                fixedLine = fixedLine
                    .Replace("\\\\", "TEMP")
                    .Replace("\\", "\\\\")
                    .Replace("TEMP", "\\\\");

                // Add source
                sb.AppendLine("@@source: 'Recorder'");
                sb.AppendLine(fixedLine);
            }

            sb.AppendLine("# End of autogenerated actions using the recorder");

            return sb.ToString();
        }

        // ============================================================
        // 🔥 FORCE DOUBLE QUOTES
        // ============================================================
        private string WrapWithQuotes(string input)
        {
            return "\"" + input.Replace("\"", "\\\"") + "\"";
        }

        // ============================================================
        // PATCH
        // ============================================================
        private async Task SendPatch(Guid flowId, JsonObject payload)
        {
            var url = $"{_orgUrl}/api/data/v9.2/workflows({flowId})";

            var req = new HttpRequestMessage(new HttpMethod("PATCH"), url)
            {
                Content = new StringContent(
                    payload.ToJsonString(),
                    Encoding.UTF8,
                    "application/json")
            };

            var res = await _httpClient.SendAsync(req);
            var body = await res.Content.ReadAsStringAsync();

            Console.WriteLine($"PATCH {(int)res.StatusCode}");
            Console.WriteLine(body);

            if (!res.IsSuccessStatusCode)
                throw new Exception(body);
        }

        // ============================================================
        // ACTIVATE
        // ============================================================
        private async Task ActivateWorkflowAsync(Guid flowId)
        {
            var url = $"{_orgUrl}/api/data/v9.2/workflows({flowId})/Microsoft.Dynamics.CRM.ActivateWorkflow";

            var req = new HttpRequestMessage(HttpMethod.Post, url)
            {
                Content = new StringContent("{}", Encoding.UTF8, "application/json")
            };

            var res = await _httpClient.SendAsync(req);

            if (!res.IsSuccessStatusCode)
            {
                var body = await res.Content.ReadAsStringAsync();
                throw new Exception(body);
            }
        }
    }
}