using System;
using System.Collections.Generic;
using System.Text;

namespace WisprDesktopAgent.Core;

/// <summary>
/// Converts WISPR RecordedStep list into Power Automate Desktop .robin script format.
/// Generates UIAutomation actions with element definitions and selectors.
/// </summary>
public class RobinScriptWriter
{
    /// <summary>
    /// Converts a list of RecordedStep objects into a .robin script string.
    /// </summary>
    public string WriteScript(List<RecordedStep> steps, string appName, string appPath)
    {
        // Check if any steps have original PAD selectors (appmask references)
        bool hasPadSelectors = false;
        for (int i = 0; i < steps.Count; i++)
        {
            if (!string.IsNullOrEmpty(steps[i].PadSelector) && steps[i].PadSelector.Contains("appmask["))
            {
                hasPadSelectors = true;
                break;
            }
        }

        if (hasPadSelectors)
            return WriteNativePadScript(steps, appName, appPath);
        else
            return WriteGenericScript(steps, appName, appPath);
    }

    /// <summary>
    /// Writes a .robin script that preserves original PAD appmask selectors.
    /// This is used when steps were imported from a PAD recording and already have valid selectors.
    /// </summary>
    private string WriteNativePadScript(List<RecordedStep> steps, string appName, string appPath)
    {
        var sb = new StringBuilder();

        // Standard PAD header
        sb.AppendLine("@@Type: 'Local'");
        sb.AppendLine("@@DesktopType: 'local'");
        sb.AppendLine("@@DisplayName: 'Local computer'");
        sb.AppendLine("IMPORT 'controlRepo.appmask' AS appmask");
        sb.AppendLine("IMPORT 'imageRepo.imgrepo' AS imgrepo");
        sb.AppendLine("@SENSITIVE: []");
        sb.AppendLine("# Generated by WISPR Desktop Test Recorder");
        sb.AppendLine("# Application: " + appName);
        sb.AppendLine("# Date: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));

        // Launch application if path is provided and first step isn't already a launch
        if (!string.IsNullOrEmpty(appPath) && (steps.Count == 0 || steps[0].Action != "launch_app"))
        {
            sb.AppendLine("System.LaunchApplication ApplicationPath: $'''" + appPath + "''' WindowStyle: System.ProcessWindowStyle.Normal");
            sb.AppendLine("WAIT 2");
        }

        // Generate actions using original PAD selectors
        for (int i = 0; i < steps.Count; i++)
        {
            var step = steps[i];
            sb.AppendLine("@@source: 'Recorder'");

            string padSel = step.PadSelector;
            string action = step.Action;
            if (string.IsNullOrEmpty(action)) action = "click";

            if (action == "type")
            {
                string text = step.Value ?? "";
                // Check if value looks like an encrypted PAD password (P'AQ...)
                bool isEncrypted = text.StartsWith("P'") && text.EndsWith("'");
                string textLiteral = isEncrypted ? text : "'" + text + "'";

                if (!string.IsNullOrEmpty(padSel) && padSel.Contains("appmask["))
                {
                    sb.AppendLine("UIAutomation.PopulateTextField.PopulateTextField TextField: " + padSel +
                        " Text: " + textLiteral +
                        " Mode: UIAutomation.PopulateTextMode.Replace ClickType: UIAutomation.PopulateMouseClickType.SingleClick");
                }
                else
                {
                    sb.AppendLine("UIAutomation.PopulateTextField.PopulateTextField TextField: " + BuildInlinePadSelector(step) +
                        " Text: " + textLiteral +
                        " Mode: UIAutomation.PopulateTextMode.Replace ClickType: UIAutomation.PopulateMouseClickType.SingleClick");
                }
            }
            else if (action == "click" || action == "double_click" || action == "right_click")
            {
                if (!string.IsNullOrEmpty(padSel) && padSel.Contains("appmask["))
                {
                    sb.AppendLine("UIAutomation.PressButton Button: " + padSel);
                }
                else
                {
                    sb.AppendLine("UIAutomation.PressButton Button: " + BuildInlinePadSelector(step));
                }
            }
            else if (action == "select")
            {
                string item = step.Value ?? "";
                if (!string.IsNullOrEmpty(padSel) && padSel.Contains("appmask["))
                {
                    sb.AppendLine("UIAutomation.SelectDropDownListItem Element: " + padSel + " Item: '" + item + "'");
                }
                else
                {
                    sb.AppendLine("UIAutomation.SelectDropDownListItem Element: " + BuildInlinePadSelector(step) + " Item: '" + item + "'");
                }
            }
            else if (action == "wait")
            {
                string duration = step.Value;
                if (string.IsNullOrEmpty(duration)) duration = "2";
                sb.AppendLine("WAIT " + duration);
            }
            else if (action == "launch_app")
            {
                string path = step.Value ?? "";
                sb.AppendLine("System.LaunchApplication ApplicationPath: $'''" + path + "''' WindowStyle: System.ProcessWindowStyle.Normal");
            }
            else if (action == "keyboard_shortcut")
            {
                string keys = step.Value ?? "";
                sb.AppendLine("MouseAndKeyboard.SendKeys TextToSend: $'''" + keys + "''' DelayBetweenKeystrokes: 10");
            }
            else if (action == "window_close")
            {
                if (!string.IsNullOrEmpty(padSel) && padSel.Contains("appmask["))
                    sb.AppendLine("UIAutomation.PressButton Button: " + padSel);
                else
                    sb.AppendLine("UIAutomation.PressButton Button: " + BuildInlinePadSelector(step));
            }
            else
            {
                sb.AppendLine("# WISPR Action: " + action + " " + step.Label);
            }
        }

        sb.AppendLine("# End of autogenerated actions using the recorder");
        return sb.ToString();
    }

    /// <summary>
    /// Builds an inline appmask-style selector for steps that don't have an original PAD selector.
    /// </summary>
    private string BuildInlinePadSelector(RecordedStep step)
    {
        string window = step.ParentWindow;
        if (string.IsNullOrEmpty(window))
            window = ExtractFromWindowSelector(step.WindowSelector, "title");
        if (string.IsNullOrEmpty(window))
            window = "Application";

        string elementName = step.Label;
        if (string.IsNullOrEmpty(elementName))
            elementName = step.AutomationId;
        if (string.IsNullOrEmpty(elementName))
            elementName = "Element";

        // Escape single quotes in window/element names for appmask format
        string escapedWindow = window.Replace("'", "\\'");
        string escapedElement = elementName.Replace("'", "\\'");

        return "appmask['Window \\'" + escapedWindow + "\\'']['" + escapedElement + "']";
    }

    /// <summary>
    /// Writes a generic .robin script for steps without PAD selectors (UIA/JAB-originated steps).
    /// Uses element definitions with desktop selectors.
    /// </summary>
    private string WriteGenericScript(List<RecordedStep> steps, string appName, string appPath)
    {
        var sb = new StringBuilder();
        var elementDefs = new Dictionary<string, string>();
        int elementCounter = 0;

        // Header
        sb.AppendLine("# Generated by WISPR Desktop Test Recorder");
        sb.AppendLine("# Application: " + appName);
        sb.AppendLine("# Date: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
        sb.AppendLine();

        // Launch application if path is provided
        if (!string.IsNullOrEmpty(appPath))
        {
            sb.AppendLine("System.LaunchApplication ApplicationPath: $'''" + appPath + "''' WindowStyle: System.ProcessWindowStyle.Normal");
            sb.AppendLine("WAIT 2");
            sb.AppendLine();
        }

        // Process each step
        for (int i = 0; i < steps.Count; i++)
        {
            var step = steps[i];

            // Build PAD selector for this step
            string padSelector = BuildPadSelector(step);
            string elementName = "";

            if (!string.IsNullOrEmpty(padSelector))
            {
                // Create element definition if selector exists
                elementName = "element_" + elementCounter;
                elementCounter++;
                elementDefs[elementName] = padSelector;
            }

            // Generate the action line
            string actionLine = GenerateActionLine(step, elementName);
            if (!string.IsNullOrEmpty(actionLine))
            {
                sb.AppendLine(actionLine);
            }
        }

        // Append element definitions at the end
        if (elementDefs.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("# [ControlRepository]");
            foreach (var kvp in elementDefs)
            {
                sb.AppendLine("ELEMENT " + kvp.Key + " @'" + kvp.Value + "'");
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Builds a PAD-format selector from a RecordedStep.
    /// Format: :desktop > window[Name="..."][Process="..."] > controlType[Name="..."]
    /// </summary>
    private string BuildPadSelector(RecordedStep step)
    {
        var parts = new List<string>();
        parts.Add(":desktop");

        // Add window segment
        string windowName = step.ParentWindow;
        if (string.IsNullOrEmpty(windowName))
        {
            // Try to extract from WindowSelector XML
            windowName = ExtractFromWindowSelector(step.WindowSelector, "title");
        }
        string processName = ExtractFromWindowSelector(step.WindowSelector, "app");

        if (!string.IsNullOrEmpty(windowName) || !string.IsNullOrEmpty(processName))
        {
            var windowSeg = new StringBuilder("window");
            if (!string.IsNullOrEmpty(windowName))
                windowSeg.Append("[Name=\"" + EscapeSelectorValue(windowName) + "\"]");
            if (!string.IsNullOrEmpty(processName))
                windowSeg.Append("[Process=\"" + EscapeSelectorValue(processName) + "\"]");
            parts.Add(windowSeg.ToString());
        }

        // Add element segment
        string controlType = MapWisprToPadControlType(step.ControlType);
        if (string.IsNullOrEmpty(controlType))
            controlType = "control";

        var elemSeg = new StringBuilder(controlType);
        bool hasAttr = false;

        if (!string.IsNullOrEmpty(step.AutomationId))
        {
            elemSeg.Append("[AutomationId=\"" + EscapeSelectorValue(step.AutomationId) + "\"]");
            hasAttr = true;
        }
        if (!string.IsNullOrEmpty(step.Label))
        {
            elemSeg.Append("[Name=\"" + EscapeSelectorValue(step.Label) + "\"]");
            hasAttr = true;
        }
        if (!string.IsNullOrEmpty(step.ClassHint))
        {
            elemSeg.Append("[Class=\"" + EscapeSelectorValue(step.ClassHint) + "\"]");
            hasAttr = true;
        }

        if (!hasAttr && string.IsNullOrEmpty(step.Label) && string.IsNullOrEmpty(step.AutomationId))
            return ""; // Can't build a meaningful selector

        parts.Add(elemSeg.ToString());

        return string.Join(" > ", parts.ToArray());
    }

    /// <summary>
    /// Generates a .robin action line for a given step.
    /// </summary>
    private string GenerateActionLine(RecordedStep step, string elementName)
    {
        string elementRef = string.IsNullOrEmpty(elementName) ? "" : " Element: %" + elementName + "%";

        string action = step.Action;
        if (string.IsNullOrEmpty(action)) action = "click";

        if (action == "click")
            return "UIAutomation.Click" + elementRef + " ClickType: UIAutomation.ClickType.LeftClick";

        if (action == "double_click")
            return "UIAutomation.Click" + elementRef + " ClickType: UIAutomation.ClickType.DoubleClick";

        if (action == "right_click")
            return "UIAutomation.Click" + elementRef + " ClickType: UIAutomation.ClickType.RightClick";

        if (action == "type")
        {
            string text = step.Value;
            if (string.IsNullOrEmpty(text)) text = "";
            return "UIAutomation.PopulateTextField" + elementRef + " Text: $'''" + text + "'''";
        }

        if (action == "clear")
            return "UIAutomation.PopulateTextField" + elementRef + " Text: $''''''";

        if (action == "select")
        {
            string item = step.Value;
            if (string.IsNullOrEmpty(item)) item = "";
            return "UIAutomation.SelectDropDownListItem" + elementRef + " Item: $'''" + item + "'''";
        }

        if (action == "hover")
            return "UIAutomation.Hover" + elementRef;

        if (action == "wait")
        {
            string duration = step.Value;
            if (string.IsNullOrEmpty(duration)) duration = "2";
            return "WAIT " + duration;
        }

        if (action == "wait_for_element")
            return "UIAutomation.WaitForUiElement" + elementRef + " Timeout: 30";

        if (action == "window_switch")
            return "UIAutomation.FocusWindow" + elementRef;

        if (action == "window_close")
            return "UIAutomation.CloseWindow" + elementRef;

        if (action == "screenshot")
            return "UIAutomation.TakeScreenshot" + elementRef;

        if (action == "launch_app")
        {
            string path = step.Value;
            if (string.IsNullOrEmpty(path)) path = "";
            return "System.LaunchApplication ApplicationPath: $'''" + path + "''' WindowStyle: System.ProcessWindowStyle.Normal";
        }

        if (action == "keyboard_shortcut")
        {
            string keys = step.Value;
            if (string.IsNullOrEmpty(keys)) keys = "";
            return "MouseAndKeyboard.SendKeys TextToSend: $'''" + keys + "''' DelayBetweenKeystrokes: 10";
        }

        if (action == "scroll")
            return "# WISPR Scroll action (manual mapping required)";

        if (action == "drag_drop")
            return "UIAutomation.DragAndDrop" + elementRef;

        if (action == "assert_text" || action == "assert_state" || action == "assert_visible")
            return "# WISPR Assertion: " + action + " (not directly supported in PAD — use conditional block)";

        // Fallback
        return "# WISPR Action: " + action + " " + step.Label;
    }

    /// <summary>
    /// Maps WISPR control types back to PAD selector control type names.
    /// </summary>
    private string MapWisprToPadControlType(string wisprType)
    {
        if (string.IsNullOrEmpty(wisprType)) return "";
        if (wisprType == "Button") return "button";
        if (wisprType == "Edit") return "edit";
        if (wisprType == "ComboBox") return "combobox";
        if (wisprType == "CheckBox") return "checkbox";
        if (wisprType == "RadioButton") return "radiobutton";
        if (wisprType == "List") return "list";
        if (wisprType == "ListItem") return "listitem";
        if (wisprType == "Tree") return "tree";
        if (wisprType == "TreeItem") return "treeitem";
        if (wisprType == "Tab") return "tab";
        if (wisprType == "TabItem") return "tabitem";
        if (wisprType == "Menu") return "menu";
        if (wisprType == "MenuItem") return "menuitem";
        if (wisprType == "DataGrid") return "datagrid";
        if (wisprType == "Text") return "text";
        if (wisprType == "Image") return "image";
        if (wisprType == "Hyperlink") return "hyperlink";
        if (wisprType == "Window") return "window";
        if (wisprType == "Pane") return "pane";
        if (wisprType == "Group") return "group";
        return wisprType.ToLower();
    }

    /// <summary>
    /// Extracts an attribute from WISPR XML window selector.
    /// e.g., ExtractFromWindowSelector("<wnd app=\"calc.exe\" title=\"Calc\" />", "app") returns "calc.exe"
    /// </summary>
    private string ExtractFromWindowSelector(string windowSelector, string attrName)
    {
        if (string.IsNullOrEmpty(windowSelector)) return "";
        string pattern = attrName + @"=""([^""]*)""";
        var match = System.Text.RegularExpressions.Regex.Match(windowSelector, pattern);
        if (match.Success) return match.Groups[1].Value;
        return "";
    }

    /// <summary>
    /// Escapes a value for use in PAD selector attributes.
    /// </summary>
    private string EscapeSelectorValue(string value)
    {
        if (string.IsNullOrEmpty(value)) return "";
        return value.Replace("\"", "\\\"");
    }
}
