// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfjeicrvelgmyyecvlxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmamVpY3J2ZWxnbXl5ZWN2bHhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5NjgwNDcsImV4cCI6MjA3OTU0NDA0N30.HntMCQgGp7PmfryCvilswUNOvyTHuRPYdTgZGvY6z7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'pkce',
  }
});